FROM  golang:1.17-alpine as builder

WORKDIR /project/capstone

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .
RUN go build -tags tools -o /project/capstone/build/capstone-tools .

FROM alpine:latest
COPY --from=builder /project/capstone/build/capstone-tools /project/capstone/build/capstone-tools

ENTRYPOINT [ "sleep", "infinity" ]
