// Code generated by "go run clinic-pilot/tool/stringer -linecomment -type=CategoryLogoType -output=category_enum_gen.go -swagoutput=../tool/swag/enum_gen/category_enum_gen.go -custom"; DO NOT EDIT.

package enum_gen

import (
	"github.com/go-openapi/spec"
)

func init() {
	PostSwaggerDefinitions["CategoryLogoTypeEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"FOOD_BEVERAGE",
				"TRANSPORTATION",
				"RENTAL",
				"WATER_BILL",
				"PHONE_BILL",
				"ELECTRICITY_BILL",
				"EDUCATION",
				"PETS",
				"FITNESS",
				"GAMES",
				"OTHER",
			},
		},
	}
}
